########################### FRONT-OFFICE #############################

cm_front_home:
   path: /
   controller: App\Controller\Front\HomeController::indexAction

############################## USERS #################################
cm_back_admin_user_edit:
    path: /back/admin-user-edit
    controller: App\Controller\Back\UserController::adminUserEditAction

login:
    path: /login
    defaults:
        _controller: App\Controller\SecurityController:loginAction

login_check:
    path: /login_check

logout:
    path: /logout

########################### BACK-OFFICE ##############################

# Dashboard #

cm_back_dashboard:
    path:     /back
    controller: App\Controller\Back\GlobalController::indexAction

# Bio #

cm_back_bio:
    path:    /back/bio
    controller:   App\Controller\Back\BioController::defaultAction

# Irl #

cm_back_irl_list:
    path:    /back/irl
    controller:   App\Controller\Back\IrlController::listAction

cm_back_irl_single:
    path:    /back/irl/{id}
    controller:   App\Controller\Back\IrlController::singleAction
    requirements:
       id: \d+

cm_back_irl_add:
    path:    /back/irl/add
    controller:   App\Controller\Back\IrlController::addAction

cm_back_irl_delete:
    path:    /back/irl/delete/{id}
    controller:   App\Controller\Back\IrlController::deleteAction
    requirements:
       id: \d+

cm_back_irl_toggle_published:
    path:    /back/irl/togglepublished/{id}
    controller:   App\Controller\Back\IrlController::togglePublishedAction
    requirements:
       id: \d+


# Technologies #

cm_back_technology_list:
    path:    /back/technologies/{id}
    controller:   App\Controller\Back\TechnologyController::listAction
    requirements:
       id: \d+
    defaults:
       id: null

cm_back_technology_category_delete:
    path:    /back/technologies/delete-category/{id}
    controller:   App\Controller\Back\TechnologyController::categoryDeleteAction
    requirements:
       id: \d+

cm_back_technology_single:
    path:    /back/technology/{id}
    controller:   App\Controller\Back\TechnologyController::singleAction
    requirements:
       id: \d+

cm_back_technology_add:
    path:    /back/technology/add
    controller:   App\Controller\Back\TechnologyController::addAction


cm_back_technology_delete:
    path:    /back/technology/delete/{id}
    controller:   App\Controller\Back\TechnologyController::deleteAction
    requirements:
       id: \d+

cm_back_technology_toggle_mastered:
    path:    /back/technology/toggle-mastered/{id}
    controller:   App\Controller\Back\TechnologyController::toggleMasteredAction
    requirements:
       id: \d+

cm_back_technology_toggle_published:
    path:    /back/technology/toggle-published/{id}
    controller:   App\Controller\Back\TechnologyController::togglePublishedAction
    requirements:
       id: \d+

# Productions #

cm_back_production_list:
    path:    /back/productions/{id}
    controller:   App\Controller\Back\ProductionController::listAction
    requirements:
       id: \d+
    defaults:
       id: null

cm_back_production_single:
    path:    /back/production/{id}
    controller:   App\Controller\Back\ProductionController::singleAction
    requirements:
       id: \d+

cm_back_production_add:
    path:    /back/production/add
    controller:   App\Controller\Back\ProductionController::addAction


cm_back_production_delete:
    path:    /back/production/delete/{id}
    controller:   App\Controller\Back\ProductionController::deleteAction
    requirements:
       id: \d+

cm_back_production_toggle_published:
    path:    /back/production/toggle-published/{id}
    controller:   App\Controller\Back\ProductionController::togglePublishedAction
    requirements:
       id: \d+

cm_back_production_category_delete:
    path:    /back/production-categories/delete/{id}
    controller:   App\Controller\Back\ProductionController::categoryDeleteAction
    requirements:
       id: \d+


# Career #

cm_back_career_list:
   path: /back/career/{id}
   controller: App\Controller\Back\CareerController::listAction
   requirements:
      id: \d+
   defaults:
      id: null

cm_back_career_delete:
    path:    /back/career/delete/{id}
    controller:   App\Controller\Back\CareerController::deleteAction
    requirements:
       id: \d+

cm_back_career_toggle_published:
    path:    /back/career/toggle-published/{id}
    controller:   App\Controller\Back\CareerController::togglePublishedAction
    requirements:
       id: \d+

# Messages #

cm_back_message_list:
   path: /back/messages/{id}
   controller: App\Controller\MessageController::listAction
   requirements:
      id: \d+
   defaults:
      id: null

cm_back_message_delete:
    path:    /back/message/delete/{id}
    controller:   App\Controller\MessageController::deleteAction
    requirements:
      id: \d+

cm_back_message_toggle_processed:
    path:    /back/message/toggle-processed/{id}
    controller:   App\Controller\MessageController::toggleProcessedAction
    requirements:
      id: \d+
